

version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 # Expose the port 27017 to the host machine
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes: # Persist the data
      - ./mongo:/data/db